### configuration for develop
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wequan
    username: wequan_admin
    password: wequan@bu

logging:
  level:
#    root: debug
    com.wequan.bu.repository.dao: DEBUG

# email service configuration
sendcloud:
  email:
    api-user: ccyzhope_test_u1jCHY
    api-key: CqI5QkoXFgIKdATU
    domain: 9FxtC4peFpLuxKZPt2XaoHXuwkyiV3tP.sendcloud.org

swagger:
  enable: true
  title: ${spring.application.name} Restful API
  description: ${spring.application.name} Restful API
  termsOfServiceUrl: https://github.com/yonhenli
  contact:
    name: Yongheng Li
    url: https://github.com/yonhenli
    email: yli241@binghamton.edu
  version: 1.0
  base-package: com.wequan.bu.controller