### common configuration for project
# configuration for https
server:
  port: 443
  servlet:
    context-path: /api
  ssl:
    key-store: classpath:cert/https_dev_cert.jks
    key-store-password: quanzi@bu
    key-store-type: pkcs12
# configuration for http
http:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: Quan_Zi
  transaction:
    rollback-on-commit-failure: true
  messages:
    basename: i18n/messages
  jackson:
    parser:
      ALLOW_SINGLE_QUOTES: true
      ALLOW_UNQUOTED_FIELD_NAMES: true
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.quanzi.bu.repository.dao
  configuration:
    map-underscore-to-camel-case: true
  configuration-properties:
    schema: bu

logging:
  level:
    root: info

log:
  path: log