### common configuration for project
# configuration for https
server:
  port: 443
  servlet:
    context-path: /api
  ssl:
    key-store: classpath:cert/https_dev_cert.jks
    key-store-password: quanzi@bu
    key-store-type: pkcs12
# configuration for http
http:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: We_Quan
  transaction:
    rollback-on-commit-failure: true
  messages:
    basename: i18n/messages
  jackson:
    parser:
      ALLOW_SINGLE_QUOTES: true
      ALLOW_UNQUOTED_FIELD_NAMES: true
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.wequan.bu.repository.dao
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    cache-enabled: true
#    interceptors:
#      -
  lazy-initialization: true
  configuration-properties:
    schema: bu

pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

logging:
  level:
    root: info

log:
  path: log

app:
  user:
    profile-location: profile