### common configuration for project
# configuration for https
server:
  port: 443
  servlet:
    context-path: /api
  ssl:
    key-store: classpath:cert/https_dev_cert.jks
    key-store-password: quanzi@bu
    key-store-type: pkcs12
# configuration for http
http:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: We_Quan
  transaction:
    rollback-on-commit-failure: true
  messages:
    basename: i18n/messages
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    parser:
      ALLOW_SINGLE_QUOTES: true
      ALLOW_UNQUOTED_FIELD_NAMES: true
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    quartz:
      properties:
        org:
          quartz:
            scheduler:
              instanceName: clusteredScheduler
              instanceId: AUTO
            jobStore:
              class: org.quartz.impl.jdbcjobstore.JobStoreTX
              driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
              tablePrefix: QRTZ_
              useProperties: false
              dataSource: myDs
            threadPool:
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 10
              threadPriority: 5
              threadsInheritContextClassLoaderOfInitializingThread: true
            dataSource:
              myDs:
                driver: org.postgresql.Driver
                URL: jdbc:postgresql://wequan.cgnev0a5e0ak.us-east-1.rds.amazonaws.com:5432/wequan
                user: wequan_admin
                password: wequan@bu

      jdbc-store-type: jdbc

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.wequan.bu.repository.dao
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    cache-enabled: true
#    interceptors:
#      -
  lazy-initialization: true
  configuration-properties:
    schema: bu

pagehelper:
  helperDialect: postgresql
  offset-as-page-num: true
  page-size-zero: true
  reasonable: true
  supportMethodsArguments: true

logging:
  level:
    root: info

log:
  path: log

app:
  user:
    profile-location: profile
