spring:
  profiles:
    active: dev

  main:
    web-application-type: none
    show-banner: false

im:
  port: 9000

amazon:
  aws:
    accesskey: AKIAT3UCHJRBB7WS5BUB
    secretkey: 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