package com.wequan.bu.repository.dao;

import com.wequan.bu.repository.model.ReportRecord;
import com.wequan.bu.repository.model.Thread;
import com.wequan.bu.repository.model.ThreadStream;
import com.wequan.bu.repository.model.ThreadUserSelectedSubjects;
import com.wequan.bu.repository.model.extend.ThreadBriefInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.session.RowBounds;

import java.util.Date;
import java.util.List;

@Mapper
public interface ThreadMapper extends GeneralMapper<Thread>{

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_thread
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * 6/28
     * @param record
     * @return
     */
    int insertThread(Thread record);

    /**
     *6/20
     * @param threadStream
     * @return
     */
    int insertReply(ThreadStream threadStream);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_thread
     *
     * @mbg.generated
     */
    int insertSelective(Thread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_thread
     *
     * @mbg.generated
     */
    Thread selectByPrimaryKey(Integer id);

    /**
     * 6/18
     * @param schoolId
     * @param rowBounds
     * @return
     */
    List<Thread> selectBySchoolId(Integer schoolId, RowBounds rowBounds);

    /**
     * 6/19
     * @param schoolId
     * @param tagId
     * @param rowBounds
     * @return
     */
    List<Thread> selectBySchoolIdAndTag(Integer schoolId, Integer tagId, RowBounds rowBounds);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_thread
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Thread record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_thread
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Thread record);

    /**
     * 6/20
     * @param threadId
     * @param userId
     */
    void likeThread(Integer threadId, Integer userId);

    /**
     * 6/20
     * @param threadId
     * @param userId
     */
    void dislikeThread(Integer threadId, Integer userId);

    /**
     * 6/20
     * @param threadId
     * @param replyId
     * @param userId
     */
    void likeReplyOfThread(Integer threadId, Integer replyId, Integer userId);

    /**
     * 6/20
     * @param threadId
     * @param replyId
     * @param userId
     */
    void dislikeReplyOfThread(Integer threadId, Integer replyId, Integer userId);

    /**
     * 6/22
     * @param userId
     * @param subjectsId
     */
    void addUserInterestedSubjects(Integer userId, String subjectsId);

    /**
     * 6/19
     * @param threadId
     * @param rowBounds
     * @return
     */
    List<ThreadStream> selectDirectRepliesById(Integer threadId, RowBounds rowBounds);

    /**
     * 6/22
     * @param threadId
     * @param rowBounds
     * @return
     */
    List<ThreadStream> selectIndirectRepliesById(Integer threadId, RowBounds rowBounds);

    /**
     * 6/22
     * @param userId
     * @param rowBounds
     * @return
     */
    List<Thread> selectByUserFollowingId(Integer userId, RowBounds rowBounds);

    /**
     * 6/22
     * @param userId
     * @return
     */
    ThreadUserSelectedSubjects selectUserSelectedSubjectsById(Integer userId);

    /**
     * 6/22
     * @param userId
     */
    void deleteUserSelectedSubjectsById(Integer userId);

    /**
     * 6/23
     * @param schoolId
     * @param rowBounds
     * @return
     */
    List<Thread> selectedBySchoolIdOrderedByView(Integer schoolId, RowBounds rowBounds);

    /**
     * 6/23
     * @param threadId
     * @param userId
     * @param reason
     * @param reportDate
     */
    void reportThread(Integer threadId, Integer userId, String reason, Date reportDate);

    /**
     * 6/23
     * @param threadId
     * @param replyId
     * @param userId
     * @param reason
     * @param reportDate
     */
    void reportReplyToThread(Integer threadId, Integer replyId, Integer userId, String reason, Date reportDate);

    /**
     * 6/26
     * @param userId
     * @param subjectIds
     * @return
     */
    List<Thread> getUserInterestedStudyHelpThreadsByIds(Integer userId, List<Integer> subjectIds, RowBounds rowBounds);

}