package com.wequan.bu.repository.model;

import lombok.Data;

/**
 * Database Table Remarks:
 *   辅导评价表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bu.wq_appointment_review
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class AppointmentReview {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_appointment_review.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   辅导id，关联appointment(id)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_appointment_review.appointment_id
     *
     * @mbg.generated
     */
    private Integer appointmentId;

    /**
     * Database Column Remarks:
     *   评价辅导的用户id，关联user_profile(id)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_appointment_review.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   用户评分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_appointment_review.score
     *
     * @mbg.generated
     */
    private Float score;

    /**
     * Database Column Remarks:
     *   用户评价
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_appointment_review.review
     *
     * @mbg.generated
     */
    private String review;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_appointment_review
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AppointmentReview other = (AppointmentReview) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAppointmentId() == null ? other.getAppointmentId() == null : this.getAppointmentId().equals(other.getAppointmentId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getScore() == null ? other.getScore() == null : this.getScore().equals(other.getScore()))
            && (this.getReview() == null ? other.getReview() == null : this.getReview().equals(other.getReview()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_appointment_review
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAppointmentId() == null) ? 0 : getAppointmentId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getScore() == null) ? 0 : getScore().hashCode());
        result = prime * result + ((getReview() == null) ? 0 : getReview().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_appointment_review
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", appointmentId=").append(appointmentId);
        sb.append(", userId=").append(userId);
        sb.append(", score=").append(score);
        sb.append(", review=").append(review);
        sb.append("]");
        return sb.toString();
    }
}