package com.wequan.bu.repository.model;

import lombok.Data;

import java.util.Date;

/**
 * Database Table Remarks:
 *   Tutor被查看历史纪录
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bu.wq_tutor_view_history
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class TutorViewHistory {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_view_history.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   用户id，关联user_profile(id)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_view_history.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   tutor id，关联tutor_profile(id)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_view_history.tutor_id
     *
     * @mbg.generated
     */
    private Integer tutorId;

    /**
     * Database Column Remarks:
     *   Tutor被查看时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_view_history.view_time
     *
     * @mbg.generated
     */
    private Date viewTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_tutor_view_history
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TutorViewHistory other = (TutorViewHistory) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getTutorId() == null ? other.getTutorId() == null : this.getTutorId().equals(other.getTutorId()))
            && (this.getViewTime() == null ? other.getViewTime() == null : this.getViewTime().equals(other.getViewTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_tutor_view_history
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getTutorId() == null) ? 0 : getTutorId().hashCode());
        result = prime * result + ((getViewTime() == null) ? 0 : getViewTime().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_tutor_view_history
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", tutorId=").append(tutorId);
        sb.append(", viewTime=").append(viewTime);
        sb.append("]");
        return sb.toString();
    }
}