package com.wequan.bu.repository.model;

import lombok.Data;

import java.util.Date;

/**
 * Database Table Remarks:
 *   申请Tutor日志
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bu.wq_tutor_application_log
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class TutorApplicationLog {
    /**
     * Database Column Remarks:
     *   用户id，关联user_profile(id)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application_log.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   action类别
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application_log.action
     *
     * @mbg.generated
     */
    private Integer action;

    /**
     * Database Column Remarks:
     *   action时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application_log.action_time
     *
     * @mbg.generated
     */
    private Date actionTime;

    /**
     * Database Column Remarks:
     *   简要概述action
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application_log.action_log
     *
     * @mbg.generated
     */
    private String actionLog;

    /**
     * Database Column Remarks:
     *   Tutor申请id，关联tutor_application(id)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application_log.tutor_application_id
     *
     * @mbg.generated
     */
    private Integer tutorApplicationId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_tutor_application_log
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TutorApplicationLog other = (TutorApplicationLog) that;
        return (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getAction() == null ? other.getAction() == null : this.getAction().equals(other.getAction()))
            && (this.getActionTime() == null ? other.getActionTime() == null : this.getActionTime().equals(other.getActionTime()))
            && (this.getActionLog() == null ? other.getActionLog() == null : this.getActionLog().equals(other.getActionLog()))
            && (this.getTutorApplicationId() == null ? other.getTutorApplicationId() == null : this.getTutorApplicationId().equals(other.getTutorApplicationId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_tutor_application_log
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getAction() == null) ? 0 : getAction().hashCode());
        result = prime * result + ((getActionTime() == null) ? 0 : getActionTime().hashCode());
        result = prime * result + ((getActionLog() == null) ? 0 : getActionLog().hashCode());
        result = prime * result + ((getTutorApplicationId() == null) ? 0 : getTutorApplicationId().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_tutor_application_log
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", action=").append(action);
        sb.append(", actionTime=").append(actionTime);
        sb.append(", actionLog=").append(actionLog);
        sb.append(", tutorApplicationId=").append(tutorApplicationId);
        sb.append("]");
        return sb.toString();
    }
}