package com.wequan.bu.repository.model;

import lombok.Data;

import java.util.Date;
import java.util.List;

/**
 * Database Table Remarks:
 *   申请Tutor的历史记录，同时用于审核
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bu.wq_tutor_application
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class TutorApplication {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   申请Tutor的用户id，关联user_profile(id)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   申请Tutor的自我简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application.brief_introduction
     *
     * @mbg.generated
     */
    private String briefIntroduction;

    /**
     * Database Column Remarks:
     *   当前所在学校，关联school(id)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application.current_school_id
     *
     * @mbg.generated
     */
    private Short currentSchoolId;

    /**
     * Database Column Remarks:
     *   当前学位，关联degree(id)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application.current_degree_id
     *
     * @mbg.generated
     */
    private Short currentDegreeId;

    /**
     * Database Column Remarks:
     *   当前所在位置
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application.current_location
     *
     * @mbg.generated
     */
    private String currentLocation;

    /**
     * Database Column Remarks:
     *   形式：1,2,3(课程id的字符串)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application.apply_tutor_courses
     *
     * @mbg.generated
     */
    private String applyTutorCourses;

    /**
     * Database Column Remarks:
     *   创建/申请时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   0, default with apply; 1, admin  pass; -1,  admin reject; -2, user delete
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_tutor_application.status
     *
     * @mbg.generated
     */
    private Short status;

    private List<TutorApplicationFile> tutorApplicationFiles;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_tutor_application
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TutorApplication other = (TutorApplication) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getBriefIntroduction() == null ? other.getBriefIntroduction() == null : this.getBriefIntroduction().equals(other.getBriefIntroduction()))
            && (this.getCurrentSchoolId() == null ? other.getCurrentSchoolId() == null : this.getCurrentSchoolId().equals(other.getCurrentSchoolId()))
            && (this.getCurrentDegreeId() == null ? other.getCurrentDegreeId() == null : this.getCurrentDegreeId().equals(other.getCurrentDegreeId()))
            && (this.getCurrentLocation() == null ? other.getCurrentLocation() == null : this.getCurrentLocation().equals(other.getCurrentLocation()))
            && (this.getApplyTutorCourses() == null ? other.getApplyTutorCourses() == null : this.getApplyTutorCourses().equals(other.getApplyTutorCourses()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_tutor_application
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getBriefIntroduction() == null) ? 0 : getBriefIntroduction().hashCode());
        result = prime * result + ((getCurrentSchoolId() == null) ? 0 : getCurrentSchoolId().hashCode());
        result = prime * result + ((getCurrentDegreeId() == null) ? 0 : getCurrentDegreeId().hashCode());
        result = prime * result + ((getCurrentLocation() == null) ? 0 : getCurrentLocation().hashCode());
        result = prime * result + ((getApplyTutorCourses() == null) ? 0 : getApplyTutorCourses().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bu.wq_tutor_application
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", briefIntroduction=").append(briefIntroduction);
        sb.append(", currentSchoolId=").append(currentSchoolId);
        sb.append(", currentDegreeId=").append(currentDegreeId);
        sb.append(", currentLocation=").append(currentLocation);
        sb.append(", applyTutorCourses=").append(applyTutorCourses);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", status=").append(status);
        sb.append("]");
        return sb.toString();
    }
}