package com.wequan.bu.repository.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.Data;

import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bu.wq_user_profile
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class User {
    /**
     * Database Column Remarks:
     *   主键
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户昵称
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   用户邮箱
     */
    private String email;

    /**
     * Database Column Remarks:
     *   用户电话号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   用户通信地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   邮政编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.zip_code
     *
     * @mbg.generated
     */
    private String zipCode;

    /**
     * Database Column Remarks:
     *   用户密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.credential
     *
     * @mbg.generated
     */
    @JsonIgnore
    private String credential;

    /**
     * Database Column Remarks:
     *   所在学校id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.school_id
     *
     * @mbg.generated
     */
    private Short schoolId;

    /**
     * Database Column Remarks:
     *   用户学习积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.study_points
     *
     * @mbg.generated
     */
    private Short studyPoints;

    /**
     * Database Column Remarks:
     *   用户token
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.access_token
     *
     * @mbg.generated
     */
    private String accessToken;

    /**
     * Database Column Remarks:
     *   用户的名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     * Database Column Remarks:
     *   用户的姓
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.invitation_code
     *
     * @mbg.generated
     */
    private String invitationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.brief_introduction
     *
     * @mbg.generated
     */
    private String briefIntroduction;

    /**
     * Database Column Remarks:
     *   邮箱是否经过验证
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.email_verified
     *
     * @mbg.generated
     */
    private Boolean emailVerified;

    /**
     * Database Column Remarks:
     *   第三方名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.provider
     *
     * @mbg.generated
     */
    private String provider;

    /**
     * Database Column Remarks:
     *   第三方id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.provider_id
     *
     * @mbg.generated
     */
    private String providerId;

    /**
     * Database Column Remarks:
     *   用户在第三方应用上的头像url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.avatar_url_in_provider
     *
     * @mbg.generated
     */
    private String avatarUrlInProvider;

    /**
     * Database Column Remarks:
     *   用户头像
     */
    private byte[] avatar;

    /**
     * Database Column Remarks:
     *   创建时间
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     */
    private Date updateTime;

    private List<UserFollow> following;
    private List<UserFollow> followed;


}