package com.wequan.bu.repository.model;

import lombok.Data;

import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table bu.wq_user_profile
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class User {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   用户昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.user_name
     *
     * @mbg.generated
     */
    private String userName;

    /**
     * Database Column Remarks:
     *   用户邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   用户电话号码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   用户通信地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   邮政编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.zip_code
     *
     * @mbg.generated
     */
    private String zipCode;

    /**
     * Database Column Remarks:
     *   用户密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.credential
     *
     * @mbg.generated
     */
    private String credential;

    /**
     * Database Column Remarks:
     *   所在学校id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.school_id
     *
     * @mbg.generated
     */
    private Short schoolId;

    /**
     * Database Column Remarks:
     *   用户学习积分
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.study_points
     *
     * @mbg.generated
     */
    private Short studyPoints;

    /**
     * Database Column Remarks:
     *   用户token
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.access_token
     *
     * @mbg.generated
     */
    private String accessToken;

    /**
     * Database Column Remarks:
     *   用户的名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     * Database Column Remarks:
     *   用户的姓
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.invitation_code
     *
     * @mbg.generated
     */
    private String invitationCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.brief_introduction
     *
     * @mbg.generated
     */
    private String briefIntroduction;

    /**
     * Database Column Remarks:
     *   用户头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bu.wq_user_profile.avatar
     *
     * @mbg.generated
     */
    private byte[] avatar;

    private List<UserFollow> following;
    private List<UserFollow> followed;
}